[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/.well-known/apple-developer-merchantid-domain-association"
  [headers.values]
    Content-Type = "text/plain"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

